/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GenerateInput = IDL.Record({
  'experienceLevel' : IDL.Text,
  'resumeContent' : IDL.Opt(IDL.Text),
  'jobRole' : IDL.Text,
  'companyCulture' : IDL.Text,
  'industry' : IDL.Text,
});
export const RubricCategory = IDL.Record({
  'scoringGuide' : IDL.Vec(IDL.Text),
  'criteria' : IDL.Text,
});
export const EvaluationRubric = IDL.Record({
  'communication' : RubricCategory,
  'problemSolving' : RubricCategory,
  'technical' : RubricCategory,
  'cultureFit' : RubricCategory,
});
export const InterviewQuestions = IDL.Record({
  'situational' : IDL.Vec(IDL.Text),
  'technical' : IDL.Vec(IDL.Text),
  'behavioral' : IDL.Vec(IDL.Text),
});
export const JobDescription = IDL.Record({
  'responsibilities' : IDL.Vec(IDL.Text),
  'preferredQualifications' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
  'requiredSkills' : IDL.Vec(IDL.Text),
  'equalOpportunityStatement' : IDL.Text,
});
export const CandidateAnalysis = IDL.Record({
  'strengths' : IDL.Vec(IDL.Text),
  'skillGaps' : IDL.Vec(IDL.Text),
  'identifiedSkills' : IDL.Vec(IDL.Text),
  'experienceSummary' : IDL.Text,
});
export const CandidateScore = IDL.Record({
  'justification' : IDL.Text,
  'experienceScore' : IDL.Nat,
  'verdict' : IDL.Text,
  'skillsScore' : IDL.Nat,
  'totalScore' : IDL.Nat,
  'cultureFitScore' : IDL.Nat,
  'communicationScore' : IDL.Nat,
});
export const ScreeningCriteria = IDL.Record({
  'mustHave' : IDL.Vec(IDL.Text),
  'redFlags' : IDL.Vec(IDL.Text),
  'goodToHave' : IDL.Vec(IDL.Text),
});
export const RecruitmentResult = IDL.Record({
  'evaluationRubric' : EvaluationRubric,
  'interviewQuestions' : InterviewQuestions,
  'jobDescription' : JobDescription,
  'candidateAnalysis' : IDL.Opt(CandidateAnalysis),
  'candidateScore' : IDL.Opt(CandidateScore),
  'screeningCriteria' : ScreeningCriteria,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'generateRecruitmentArtifacts' : IDL.Func(
      [GenerateInput],
      [IDL.Variant({ 'ok' : RecruitmentResult, 'err' : IDL.Text })],
      [],
    ),
  'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GenerateInput = IDL.Record({
    'experienceLevel' : IDL.Text,
    'resumeContent' : IDL.Opt(IDL.Text),
    'jobRole' : IDL.Text,
    'companyCulture' : IDL.Text,
    'industry' : IDL.Text,
  });
  const RubricCategory = IDL.Record({
    'scoringGuide' : IDL.Vec(IDL.Text),
    'criteria' : IDL.Text,
  });
  const EvaluationRubric = IDL.Record({
    'communication' : RubricCategory,
    'problemSolving' : RubricCategory,
    'technical' : RubricCategory,
    'cultureFit' : RubricCategory,
  });
  const InterviewQuestions = IDL.Record({
    'situational' : IDL.Vec(IDL.Text),
    'technical' : IDL.Vec(IDL.Text),
    'behavioral' : IDL.Vec(IDL.Text),
  });
  const JobDescription = IDL.Record({
    'responsibilities' : IDL.Vec(IDL.Text),
    'preferredQualifications' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
    'requiredSkills' : IDL.Vec(IDL.Text),
    'equalOpportunityStatement' : IDL.Text,
  });
  const CandidateAnalysis = IDL.Record({
    'strengths' : IDL.Vec(IDL.Text),
    'skillGaps' : IDL.Vec(IDL.Text),
    'identifiedSkills' : IDL.Vec(IDL.Text),
    'experienceSummary' : IDL.Text,
  });
  const CandidateScore = IDL.Record({
    'justification' : IDL.Text,
    'experienceScore' : IDL.Nat,
    'verdict' : IDL.Text,
    'skillsScore' : IDL.Nat,
    'totalScore' : IDL.Nat,
    'cultureFitScore' : IDL.Nat,
    'communicationScore' : IDL.Nat,
  });
  const ScreeningCriteria = IDL.Record({
    'mustHave' : IDL.Vec(IDL.Text),
    'redFlags' : IDL.Vec(IDL.Text),
    'goodToHave' : IDL.Vec(IDL.Text),
  });
  const RecruitmentResult = IDL.Record({
    'evaluationRubric' : EvaluationRubric,
    'interviewQuestions' : InterviewQuestions,
    'jobDescription' : JobDescription,
    'candidateAnalysis' : IDL.Opt(CandidateAnalysis),
    'candidateScore' : IDL.Opt(CandidateScore),
    'screeningCriteria' : ScreeningCriteria,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'generateRecruitmentArtifacts' : IDL.Func(
        [GenerateInput],
        [IDL.Variant({ 'ok' : RecruitmentResult, 'err' : IDL.Text })],
        [],
      ),
    'setOpenAIApiKey' : IDL.Func([IDL.Text], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };